### PR TITLE
 #166896619 search for candidates in an assessment by  email

### PR DESCRIPTION
**Pull request by Mirriam-Maina**
#### What does this PR do?
- Allow an admin to search for candidates in an assessment by email

 #### Description of Task to be completed
- Add a search input field
- Add search icon
- Filter returned input values by email provided in search field

 #### How should this be manually tested?
- Clone this repo: `git clone https://github.com/andela/gradr`
- Run `yarn install` to setup the dependencies.
- Checkout to this branch `git checkout ft-search-by-email-166896619`
- Run `yarn develop-admin` to launch the gradr dmin dashboard
- Navigate to any assessment and search for a specific candidate by email in the list of candidates

 #### Any background context you want to provide?
- `N/A`

 #### What are the relevant pivotal tracker stories?
[#166896619](https://www.pivotaltracker.com/story/show/166896619)

 #### Screenshots (if appropriate)
***Before Typing***
Screenshot 2019-06-28 at 09 57 25

***After Typing***
Screenshot 2019-06-28 at 09 57 42

### CODE REVIEW

**Comment by njeri-ngigi** [comment]
What happens when email entered doesn't match any on the list?

**Comment by Mirriam-Maina** [comment]
> What happens when email entered doesn't match any on the list?

The list remains the same

**Comment by charlesodili** [comment]
Kindly move the search field to the extreme right of its container, so that the download button can remain where it was before - contextually close to the the filter dropdown, allowing Admins to intuit that they are downloading what they filtered with the drop down.

**Comment by Mirriam-Maina** [comment]
> Kindly move the search field to the extreme right of its container, so that the download button can remain where it was before - contextually close to the the filter dropdown, allowing Admins to intuit that they are downloading what they filtered with the drop down.

This has been done

**Comment by charlesodili** [comment]
Great work. Kindly wrap your solution in a function like we did for `clearInputValues()`. This way, we can execute it inside the `buildUI()` function when the mode is `manage`. Also better to move it from the bottom of the file.

**Pull request merged**
